server:
  port: 9004
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
spring:
  application:
    name: service-book      
  cloud:
    config: 
      label:  master
      profile:  dev
      url:  http://localhost:9001/
